### ISSUE TITLE
How to make docker container work?

### ISSUE THREAD

**Issue by kbtxwer** [nus-comparch/looppoint#2]
These are the contents from the Installaion section of README.md:
```bash 
Installation
Clone the repository and navigate to the base directory
$ git clone https://github.com/nus-comparch/looppoint.git
Follow the below steps to setup and build the artifact once you have the Sniper gitid
Build the docker image (Note that this is a one-time step.)
$ make build
Run the docker image
$ make
Build the demo applications
$ make apps
Download and build Sniper and LoopPoint tools
$ make tools
These steps should automatically download the required versions of SDE/Pin kit and Sniper
```
By execute `sudo make build`, I do build a docker image, and by execute `sudo make`, I can enter the container.
But where should I execute the following commands `make apps` and `make tools`?
If I quit the container and execute them directly on my host, it seems that the docker container didn't work. Should I enter the docker container, clone looppoint into it and then execute the last 3 commands?

**Comment by alenks** [comment]
If the docker image is built (using `make build`), you can run it using `make`. The command lets you enter the container and see that your current working directory (the base of the LoopPoint repository) is already mounted there. Then (without exiting the container) you can do `make apps && make tools`. There is no need to clone the repository again from inside the container.

**Comment by alenks** [comment]
Closing the issue as @kbtxwer is able to compile and run the tools from within the docker container.

**Comment by kbtxwer** [comment]
I replaced `${PWD}` with `$(shell pwd)` in MakeFile to makesure the current working directory is mounted on docker.
`${PWD}` only returns `""` (empty string) on my machine.
