### ISSUE TITLE
Issue pulling in PIN tarball with standard Makefile

### ISSUE THREAD

**Issue by jyoung3131** [nus-comparch/looppoint#3]
Hi @alenks,

I've been running and working with LoopPoint and enjoy the tool. However, there seems to be a change to the Intel PIN downloads that isn't picked up by the default Makefile. The download for PIN seems to hang possibly due to some embedded Javascript for the download. I was able to download the tarball using a browser addon like [cliget](https://github.com/zaidka/cliget) to generate a valid URL string, but this doesn't seem amenable to use with a script.

```
make[1]: Leaving directory '/net/netscratch/jy/looppoint/tools/src/Drivers'                                                                                   
Downloading Pin                                                                                                                                               
--2022-11-29 13:48:02--  https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.13-98189-g60a6ef199-gcc-linux.tar.gz                           
Resolving software.intel.com (software.intel.com)... 23.46.246.33, 2600:1402:b800:395::b, 2600:1402:b800:38f::b, ...                                         
Connecting to software.intel.com (software.intel.com)|23.46.246.33|:443... connected.                                                                         
HTTP request sent, awaiting response... 
```

This issue can be replicated outside of the container environment by running the following on any command-line (I used Ubuntu 20.04 and RHEL8):

```
wget --no-check-certificate https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.13-98189-g60a6ef199-gcc-linux.tar.gz
--2022-11-29 17:50:22--  https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.13-98189-g60a6ef199-gcc-linux.tar.gz
Resolving software.intel.com (software.intel.com)... 23.46.246.33, 2600:1402:b800:3af::b, 2600:1402:b800:395::b
Connecting to software.intel.com (software.intel.com)|23.46.246.33|:443... connected.
HTTP request sent, awaiting response...
```

**Comment by trevorcarlson** [comment]
@jyoung3131 thanks for this comment. There is a new issue when trying to automatically download files from Intel’s site. Changing the agent string allows the download to complete. To fix this, we moved to a [mirror of the files that we host on snipersim.org](https://github.com/snipersim/snipersim/blob/main/Makefile#L202).

**Comment by alenks** [comment]
@jyoung3131 @trevorcarlson Will look into this soon. I think the recent Pin/SDE license allows us to redistribute the kits along with our tools which could make things easier for us.
